In [2]:
from sklearn.datasets import load_iris 
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.cluster import KMeans 

data = load_iris() 
X, y = data.data, data.target 

# Supervised 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) 
model = KNeighborsClassifier(n_neighbors=3) 
model.fit(X_train, y_train) 
print("Supervised Accuracy:", model.score(X_test, y_test)) 

# Unsupervised 
kmeans = KMeans(n_clusters=3) 
kmeans.fit(X) 
print("Cluster Centers:", kmeans.cluster_centers_) 

Supervised Accuracy: 1.0
Cluster Centers: [[5.006      3.428      1.462      0.246     ]
 [5.9016129  2.7483871  4.39354839 1.43387097]
 [6.85       3.07368421 5.74210526 2.07105263]]


In [3]:
from sklearn.decomposition import PCA 
from sklearn.datasets import load_iris 
from sklearn.preprocessing import StandardScaler 

# Load dataset 
data = load_iris() 
X = data.data 

# Standardize data 
scaler = StandardScaler() 
X_scaled = scaler.fit_transform(X) 

# Apply PCA 
pca = PCA(n_components=2) 
X_pca = pca.fit_transform(X_scaled) 
print("Original Shape:", X.shape) 
print("Reduced Shape:", X_pca.shape) 
print("First 5 rows:\n", X_pca[:5]) 

Original Shape: (150, 4)
Reduced Shape: (150, 2)
First 5 rows:
 [[-2.26470281  0.4800266 ]
 [-2.08096115 -0.67413356]
 [-2.36422905 -0.34190802]
 [-2.29938422 -0.59739451]
 [-2.38984217  0.64683538]]


In [5]:
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 
from sklearn.datasets import load_iris 
from sklearn.model_selection import train_test_split 

# Load dataset 
X, y = load_iris(return_X_y=True) 

# Split data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) 

# Train model 
model = GaussianNB() 
model.fit(X_train, y_train) 

# Prediction 
y_pred = model.predict(X_test) 

# Evaluation 
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred)) 
print("Accuracy:", accuracy_score(y_test, y_pred)) 
print("Precision:", precision_score(y_test, y_pred, average='macro')) 
print("Recall:", recall_score(y_test, y_pred, average='macro')) 
print("F1 Score:", f1_score(y_test, y_pred, average='macro'))

Confusion Matrix:
 [[ 7  0  0]
 [ 0 15  0]
 [ 0  0  8]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0


In [6]:
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 
from sklearn.datasets import load_iris 
from sklearn.model_selection import train_test_split 

# Load dataset 
X, y = load_iris(return_X_y=True) 

# Split dataset 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train model 
model = DecisionTreeClassifier() 
model.fit(X_train, y_train) 

# Prediction 
y_pred = model.predict(X_test) 

# Evaluation 
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred)) 
print("Accuracy:", accuracy_score(y_test, y_pred)) 
print("Precision:", precision_score(y_test, y_pred, average='macro')) 
print("Recall:", recall_score(y_test, y_pred, average='macro')) 
print("F1 Score:", f1_score(y_test, y_pred, average='macro')) 

Confusion Matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0


In [7]:
import numpy as np 
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_absolute_error, mean_squared_error 
from sklearn.model_selection import train_test_split 

# Dataset (Study Hours vs Scores) 
X = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(-1,1) 
y = np.array([35, 40, 50, 55, 65, 70, 75, 85]) 

# Split data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train model 
model = LinearRegression() 
model.fit(X_train, y_train) 

# Prediction 
y_pred = model.predict(X_test) 

# Evaluation 
mae = mean_absolute_error(y_test, y_pred) 
mse = mean_squared_error(y_test, y_pred) 
rmse = np.sqrt(mse) 
r2 = model.score(X_test, y_test) 
print("Predicted Values:", y_pred) 
print("MAE:", mae) 
print("MSE:", mse) 
print("RMSE:", rmse) 
print("R2 Score:", r2)

Predicted Values: [83.21428571 42.5       ]
MAE: 2.1428571428571423
MSE: 4.719387755102044
RMSE: 2.172415189392222
R2 Score: 0.9906777525825144


In [9]:
from sklearn.linear_model import LogisticRegression 
from sklearn.datasets import load_breast_cancer 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 

# Load dataset (medical dataset similar to diabetes) 
X, y = load_breast_cancer(return_X_y=True) 

# Split data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) 

# Train model 
model = LogisticRegression(max_iter=10000) 
model.fit(X_train, y_train) 

# Prediction 
y_pred = model.predict(X_test) 

# Evaluation 
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred)) 
print("Accuracy:", accuracy_score(y_test, y_pred)) 
print("Precision:", precision_score(y_test, y_pred)) 
print("Recall:", recall_score(y_test, y_pred)) 
print("F1 Score:", f1_score(y_test, y_pred)) 

Confusion Matrix:
 [[41  2]
 [ 4 67]]
Accuracy: 0.9473684210526315
Precision: 0.9710144927536232
Recall: 0.9436619718309859
F1 Score: 0.9571428571428572


In [10]:
from sklearn.cluster import KMeans 
from sklearn.metrics import silhouette_score 
import numpy as np 

# Sample network data (features like packet size, time, etc.) 
X = np.array([ 
[10, 20], [12, 22], [11, 19], 
[50, 60], [52, 63], [48, 59], 
[200, 300]  # anomaly 
]) 

# Apply K-Means 
kmeans = KMeans(n_clusters=2) 
kmeans.fit(X) 
labels = kmeans.labels_ 
centroids = kmeans.cluster_centers_ 

# Evaluation 
print("Centroids:\n", centroids) 
print("Labels:", labels) 
print("Inertia:", kmeans.inertia_) 
print("Silhouette Score:", silhouette_score(X, labels))

Centroids:
 [[ 30.5  40.5]
 [200.  300. ]]
Labels: [0 0 0 0 0 0 1]
Inertia: 4745.0
Silhouette Score: 0.7597164415569377


In [3]:
from sklearn_extra.cluster import KMedoids 
from sklearn.metrics import silhouette_score 
import numpy as np 
# Sample telecom dataset (call, data, sms usage) 
X = np.array([ 
[100, 2, 50], 
[120, 3, 60], 
[110, 2.5, 55], 
[300, 10, 150], 
[320, 12, 170], 
[310, 11, 160] 
]) 
# Apply K-Medoid 
model = KMedoids(n_clusters=2, random_state=0) 
model.fit(X) 
labels = model.labels_ 
medoids = model.cluster_centers_ 
# Evaluation 
print("Medoids:\n", medoids) 
print("Labels:", labels) 
print("Cost (Inertia-like):", model.inertia_) 
print("Silhouette Score:", silhouette_score(X, labels)) 

ModuleNotFoundError: No module named 'sklearn_extra'